/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2018-10-29 08:18:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.project;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class projectList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/layout/header.jsp", Long.valueOf(1539344071005L));
    _jspx_dependants.put("/views/layout/footer.jsp", Long.valueOf(1539334823860L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>TTO TTO</title>\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"/CSS/bootstrap.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>  \r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>TTO TTO</title>\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("    \r\n");
      out.write("      .fakeimg { height: 200px; background: #aaa;}\r\n");
      out.write("      .card { margin-bottom: 20px;}\r\n");
      out.write("      a:link { color: black; text-decoration: none;}\r\n");
      out.write("      a:visited { color: black; text-decoration: none;}\r\n");
      out.write("      a:hover { color: grey; text-decoration: none;}\r\n");
      out.write("      \r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("    \r\n");
      out.write("<body>\r\n");
      out.write("    \r\n");
      out.write("    <!--header-->\r\n");
      out.write("     ");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- 선언부에 아래와 같이 명시 -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<!--header-->\r\n");
      out.write("    <div class=\"jumbotron text-center\" style=\"margin-bottom: 0; margin-top: 0\">\r\n");
      out.write("        <h1>TTO TTO</h1>\r\n");
      out.write("        <p>팀프로젝트 함께 하자!</p> \r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!--nav-->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-sm bg-dark navbar-dark sticky-top\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"#\" style = \"margin-left: 10px\">\r\n");
      out.write("            <img src = \"/img/logo_sample3.png\" style = \"width:40px; height:40px\"/>\r\n");
      out.write("        </a>\r\n");
      out.write("        \r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#collapsibleNavbar\" style = \"margin-top: 0\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"collapsibleNavbar\">   \r\n");
      out.write("            <ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"#\">MyPage</a>\r\n");
      out.write("                </li>   \r\n");
      out.write("            \r\n");
      out.write("            </ul>\r\n");
      out.write("      \r\n");
      out.write("            <!--search-->\r\n");
      out.write("            <form class=\"form-inline my-2 my-lg-0\" action=\"/action_page.php\">\r\n");
      out.write("                <input class=\"form-control mr-sm-2\" type=\"text\" placeholder=\"프로젝트를 찾아보세요!\">\r\n");
      out.write("                <button class=\"btn btn-success my-2 my-sm-0\" type=\"submit\">Search</button>\r\n");
      out.write("            </form>\r\n");
      out.write("            \r\n");
      out.write("        </div> \r\n");
      out.write("    </nav>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- body -->\r\n");
      out.write("    <div class=\"container\" style=\"margin-top:30px\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <!-- left section-->\r\n");
      out.write("            <div class=\"col-sm-4\">\r\n");
      out.write("                <h4>프로젝트 만들기</h4>\r\n");
      out.write("                <button id = \"createProjectBtn\" type = \"button\" class = \"btn btn-primary\">+ NEW 프로젝트</button>\r\n");
      out.write("                <p style = \"margin-top: 10px\">새 프로젝트를 만들어 친구들과 팀플을 시작하세요!</p>\r\n");
      out.write("                \r\n");
      out.write("                <br><br>\r\n");
      out.write("                \r\n");
      out.write("                <h4>진행중인 프로젝트</h4>\r\n");
      out.write("                <ul class=\"list-group\">\r\n");
      out.write("                    <li class=\"list-group-item d-flex justify-content-between align-items-center\">\r\n");
      out.write("                    <a href = \"#\">또또 프로젝트 </a>\r\n");
      out.write("                    <!-- 해당 프로젝트에 최근 이슈(새 댓글,게시글 등) 몇개 있는지 알려주는 badge-->\r\n");
      out.write("                    <span class=\"badge badge-primary badge-pill\">12</span>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                    <li class=\"list-group-item d-flex justify-content-between align-items-center\">\r\n");
      out.write("                    <a href= \"#\">뚜뚜 팀플</a>\r\n");
      out.write("                    <span class=\"badge badge-primary badge-pill\">50</span>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                    <li class=\"list-group-item d-flex justify-content-between align-items-center\">\r\n");
      out.write("                    <a href= \"#\">어사출또 개발 프로젝트</a>\r\n");
      out.write("                    <span class=\"badge badge-primary badge-pill\">99</span>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("        \r\n");
      out.write("                    <!--<hr class=\"d-sm-none\">-->\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- right section-->\r\n");
      out.write("            <div class=\"col-sm-8\">\r\n");
      out.write("                <h3>PROJECT ISSUE</h3>\r\n");
      out.write("                <hr>\r\n");
      out.write("            \r\n");
      out.write("                <!-- 해당 프로젝트 링크 버튼-->\r\n");
      out.write("                <div class = \"btn btn-outline-primary btn-sm\" style = \"margin-bottom: 10px\"> 또또 프로젝트</div>\r\n");
      out.write("                <!-- 해당 프로젝트 이슈 내용-->\r\n");
      out.write("                <div class = \"card text-center\">\r\n");
      out.write("                    <div class = \"card-header\">제목 :\r\n");
      out.write("                        <span id = \"issue-title\">새 아이디어 공유</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class = \"card-body\">\r\n");
      out.write("                        <div class  = \"fakeimg\">이미지 있으면 여기로 load</div>\r\n");
      out.write("                        <div>이슈 내용...</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                \r\n");
      out.write("                    <div class = \"card-footer\">\r\n");
      out.write("                        <span id = \"issue-maker-id\">bj먹방</span>\r\n");
      out.write("                        <span id = \"issue-maker-action\">님이 댓글을 달았습니다.</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            \r\n");
      out.write("                <!-- 해당 프로젝트 링크 버튼-->\r\n");
      out.write("                <div class = \"btn btn-outline-primary btn-sm\" style = \"margin-bottom: 10px\"> 뚜뚜 팀플 </div>\r\n");
      out.write("                <!-- 해당 프로젝트 이슈 내용-->\r\n");
      out.write("                <div class = \"card text-center\">\r\n");
      out.write("                    <div class = \"card-header\">제목 :\r\n");
      out.write("                        <span id = \"issue-title\">bootstrap 조사</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class = \"card-body\">\r\n");
      out.write("                        <div>이슈 내용...</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class = \"card-footer\">\r\n");
      out.write("                        <span id = \"issue-maker-id\">solsol</span>\r\n");
      out.write("                        <span id = \"issue-maker-action\">님이 새 글을 작성했습니다.</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- 해당 프로젝트 링크 버튼-->\r\n");
      out.write("                <div class = \"btn btn-outline-primary btn-sm\" style = \"margin-bottom: 10px\"> 뚜뚜 팀플 </div>\r\n");
      out.write("                <!-- 해당 프로젝트 이슈 내용-->\r\n");
      out.write("                <div class = \"card text-center\">\r\n");
      out.write("                    <div class = \"card-header\">제목 :\r\n");
      out.write("                        <span id = \"issue-title\">bootstrap 조사</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class = \"card-body\">\r\n");
      out.write("                        <div>이슈 내용...</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class = \"card-footer\">\r\n");
      out.write("                        <span id = \"issue-maker-id\">solsol</span>\r\n");
      out.write("                        <span id = \"issue-maker-action\">님이 새 글을 작성했습니다.</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- 해당 프로젝트 링크 버튼-->\r\n");
      out.write("                <div class = \"btn btn-outline-primary btn-sm\" style = \"margin-bottom: 10px\"> 뚜뚜 팀플 </div>\r\n");
      out.write("                <!-- 해당 프로젝트 이슈 내용-->\r\n");
      out.write("                <div class = \"card text-center\">\r\n");
      out.write("                    <div class = \"card-header\">제목 :\r\n");
      out.write("                        <span id = \"issue-title\">bootstrap 조사</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class = \"card-body\">\r\n");
      out.write("                        <div>이슈 내용...</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class = \"card-footer\">\r\n");
      out.write("                        <span id = \"issue-maker-id\">solsol</span>\r\n");
      out.write("                        <span id = \"issue-maker-action\">님이 새 글을 작성했습니다.</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!--Todo : loadMore 버튼 구현하기-->\r\n");
      out.write("                <!--<div id=\"loadMore\" style=\"\">\r\n");
      out.write("                    <a href=\"#\">Load More</a>\r\n");
      out.write("                </div>-->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- 선언부에 아래와 같이 명시 -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- footer -->\r\n");
      out.write("    <div class=\"jumbotron text-center\" style=\"margin-bottom:0\">\r\n");
      out.write("        <p>TTO TTO Project</p>\r\n");
      out.write("    </div>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<script type = \"text/javaxcript\" src = \"JS/bootstrap.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
