/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2018-10-29 08:11:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.or.iei.member.model.vo.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("kr.or.iei.member.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>TTO TTO </title>\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"/CSS/bootstrap.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>  \r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>TTO TTO</title>\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("    \r\n");
      out.write("      .fakeimg { height: 200px; background: #aaa;}\r\n");
      out.write("      .card { margin-bottom: 20px;}\r\n");
      out.write("      a:link { color: black; text-decoration: none;}\r\n");
      out.write("      a:visited { color: black; text-decoration: none;}\r\n");
      out.write("      a:hover { color: grey; text-decoration: none;}\r\n");
      out.write("      \r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("    \r\n");
      out.write("<body>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write(" function info_passCheck(){\r\n");
      out.write("\t var passCheck = document.getElementById(\"info_passCheck\");\r\n");
      out.write("\t\tpassCheck.style.display=\"block\";\r\n");
      out.write("\t\treturn false;\r\n");
      out.write(" }\r\n");
      out.write("</script>\r\n");

	session = request.getSession(false);
	
	if(session.getAttribute("member") != null){ // 로그인 성공 시
		Member member = (Member)session.getAttribute("member");

      out.write("\r\n");
      out.write("\t<h1>Main Page</h1>\r\n");
      out.write("\t");
      out.print( member.getUserId() );
      out.write("님 환영합니다.<br>\r\n");
      out.write("\t<a href=\"/myInfo.do\" onclick=\"return info_passCheck()\">My Page</a>\r\n");
      out.write("\t<a href=\"/logout.do\">로그아웃</a>\r\n");
      out.write("\t\r\n");
 }else{
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"jumbotron text-center\" style=\"margin-bottom:0\">\r\n");
      out.write("  <h1>TTO TTO</h1>\r\n");
      out.write("</div>\r\n");
      out.write(" \r\n");
      out.write("<nav class=\"navbar navbar-expand-sm bg-dark navbar-dark\">\r\n");
      out.write("  <a class=\"navbar-brand\" href=\"#\">TTOTTO</a> <!--로고들어갈자리-->\r\n");
      out.write("  <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#collapsibleNavbar\">\r\n");
      out.write("    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("  </button>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"collapsibleNavbar\"> \r\n");
      out.write("    </div>  \r\n");
      out.write("    <div class=\"pull-right\">\r\n");
      out.write("        <form class=\"form-inline pull-right\" action=\"/action_page.php\">\r\n");
      out.write("            <input class=\"form-control mr-sm-2\" type=\"text\" placeholder=\"(공개프로젝트만)\">\r\n");
      out.write("            <button class=\"btn btn-success\" type=\"submit\">검색</button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\" style=\"margin-top:30px\">\r\n");
      out.write("  <div class=\"row\">\r\n");
      out.write("    <div class=\"col-sm-6\">\r\n");
      out.write("      <h2>이미 계정이 있다면?</h2>\r\n");
      out.write("      <ul class=\"nav nav-pills flex-column\">\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"btn btn-primary\" href=\"/views/member/login.html\">로그인</a>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-sm-6\">\r\n");
      out.write("      <h2>회원가입</h2>\r\n");
      out.write("  <form action=\"/enroll.do\" method=\"post\">\r\n");
      out.write("    <div class=\"form-group\">\r\n");
      out.write("        <label for=\"id\">ID</label>\r\n");
      out.write("        <input type=\"text\" class=\"form-control\" id=\"id\" placeholder=\"아이디 입력\" name=\"userId\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form-group\">\r\n");
      out.write("      <label for=\"pwd\">Password</label>\r\n");
      out.write("      <input type=\"password\" class=\"form-control\" id=\"pwd\" placeholder=\"비밀번호 입력\" name=\"userPwd\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form-group\">\r\n");
      out.write("      <label for=\"pwd_re\">Password_re</label>\r\n");
      out.write("      <input type=\"password\" class=\"form-control\" id=\"pwd\" placeholder=\"비밀번호 재입력\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form-group\">\r\n");
      out.write("      <label for=\"email\">Email</label>\r\n");
      out.write("      <input type=\"email\" class=\"form-control\" id=\"email\" placeholder=\"이메일 입력\" name=\"userEmail\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form-group\">\r\n");
      out.write("      <label for=\"phone\">Phone</label>\r\n");
      out.write("      <input type=\"text\" class=\"form-control\" id=\"phone\" placeholder=\"전화번호 입력\" name=\"Phone\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <a href=\"#\">이메일 확인</a><br><br>\r\n");
      out.write("    <button type=\"submit\" class=\"btn btn-primary\">회원가입</button>\r\n");
      out.write("  </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"jumbotron text-center\" style=\"margin-bottom:0\">\r\n");
      out.write("  <p>Footer</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- MyPage 비밀번호 확인 -->\r\n");
      out.write("<div style=\"display:none;\" id=\"info_passCheck\">\r\n");
      out.write("\t<center>\r\n");
      out.write("\t<span style=\"color:red;\">\r\n");
      out.write("\t개인 정보 보호를 위하여 확인 차 비밀번호를 입력해 주세요.\r\n");
      out.write("\t</span>\r\n");
      out.write("\t<form action=\"/views/member/memberMyInfo.jsp\" method=\"post\">\r\n");
      out.write("\t\t비밀번호 입력 : <input type=\"password\" name=\"userPwd\" id=\"userPwd\"/>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"체크\"/>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</center>\r\n");
      out.write("</div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<script type = \"text/javaxcript\" src = \"JS/bootstrap.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
